import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import compression from 'compression';
import authRoutes from './routes/auth.js';
import userRoutes from './routes/users.js';
import peopleRoutes from './routes/people.js';
import vaultRoutes from './routes/vaults.js';
import exchangeRoutes from './routes/exchange.js';
import moneyRoutes from './routes/money.js';
import cashRoutes from './routes/cash.js';
import reportRoutes from './routes/reports.js';
import statementRoutes from './routes/statements.js';
import invoiceRoutes from './routes/invoices.js';
import adminRoutes from './routes/admin.js';
import journalRoutes from './routes/journal.js';
import ledgerRoutes from './routes/ledgers.js';
import openingBalanceRoutes from './routes/openingBalances.js';
import reconciliationRoutes from './routes/reconciliation.js';
import dailyClosingRoutes from './routes/dailyClosing.js';
import currencyRoutes from './routes/currencies.js';
import exchangeProfitRoutes from './routes/exchangeProfit.js';
import activityRoutes from './routes/activity.js';
import searchRoutes from './routes/search.js';
import dashboardStatsRoutes from './routes/dashboardStats.js';
import exportRoutes from './routes/exports.js';
import systemRoutes from './routes/system.js';
import calendarRoutes from './routes/calendar.js';
import notificationRoutes from './routes/notifications.js';
import staffIsolationRoutes from './routes/staffIsolation.js';
import securityRoutes from './routes/security.js';
import userDashboardRoutes from './routes/userDashboard.js';
import adminDashboardRoutes from './routes/adminDashboard.js';
import phase6Routes from './routes/phase6.js';
import { authenticate } from './middleware/auth.js';
import { errorHandler, notFound } from './middleware/error.js';
import { activityLogger } from './middleware/activityLogger.js';
import { apiLimiter, requestId, requireJson, sanitizeBody } from './middleware/security.js';
import { apiAccessLogger } from './middleware/apiLogger.js';

const app = express();

app.use(requestId);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true }));
app.use(compression());
app.use(apiLimiter);
app.use(express.json({ limit: process.env.JSON_LIMIT || '1mb' }));
app.use(requireJson);
app.use(sanitizeBody);
app.use(apiAccessLogger);
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));

app.get('/api/health', (req, res) => res.json({ status: 'ok', app: 'CFM Simple API', version: '3.2 Phase 6' }));
app.use('/api/auth', authRoutes);
app.use('/api/users', authenticate, activityLogger, userRoutes);
app.use('/api/people', authenticate, activityLogger, peopleRoutes);
app.use('/api/vaults', authenticate, activityLogger, vaultRoutes);
app.use('/api/exchange', authenticate, activityLogger, exchangeRoutes);
app.use('/api/money', authenticate, activityLogger, moneyRoutes);
app.use('/api/cash', authenticate, activityLogger, cashRoutes);
app.use('/api/reports', authenticate, activityLogger, reportRoutes);
app.use('/api/statements', authenticate, activityLogger, statementRoutes);
app.use('/api/invoices', authenticate, activityLogger, invoiceRoutes);
app.use('/api/admin', authenticate, activityLogger, adminRoutes);
app.use('/api/journal', authenticate, activityLogger, journalRoutes);
app.use('/api/ledgers', authenticate, activityLogger, ledgerRoutes);
app.use('/api/opening-balances', authenticate, activityLogger, openingBalanceRoutes);
app.use('/api/reconciliation', authenticate, activityLogger, reconciliationRoutes);
app.use('/api/daily-closing', authenticate, activityLogger, dailyClosingRoutes);
app.use('/api/currencies', authenticate, activityLogger, currencyRoutes);
app.use('/api/exchange-profit', authenticate, activityLogger, exchangeProfitRoutes);
app.use('/api/activity', authenticate, activityLogger, activityRoutes);
app.use('/api/search', authenticate, activityLogger, searchRoutes);
app.use('/api/dashboard-stats', authenticate, activityLogger, dashboardStatsRoutes);
app.use('/api/dashboard', authenticate, activityLogger, dashboardStatsRoutes);
app.use('/api/exports', authenticate, activityLogger, exportRoutes);
app.use('/api/system', authenticate, activityLogger, systemRoutes);
app.use('/api/calendar', authenticate, activityLogger, calendarRoutes);
app.use('/api/notifications', authenticate, activityLogger, notificationRoutes);
app.use('/api/staff-isolation', authenticate, activityLogger, staffIsolationRoutes);
app.use('/api/security', authenticate, activityLogger, securityRoutes);
app.use('/api/user-dashboard', authenticate, activityLogger, userDashboardRoutes);
app.use('/api/admin-dashboard', authenticate, activityLogger, adminDashboardRoutes);
app.use('/api/phase6', authenticate, activityLogger, phase6Routes);

app.use(notFound);
app.use(errorHandler);

export default app;
