import { useEffect, useState } from 'react';
import api from '../services/api';
import PageHeader from '../components/PageHeader';
import Alert from '../components/Alert';
const today = new Date().toISOString().slice(0,10);

export default function DailyClosing(){
 const [vaults,setVaults]=useState([]),[rows,setRows]=useState([]),[preview,setPreview]=useState(null),[msg,setMsg]=useState({});
 const [form,setForm]=useState({closingDate:today,vaultId:'',countedClosing:'',notes:''});
 async function load(){const [v,d]=await Promise.all([api.get('/vaults'),api.get('/daily-closing')]); setVaults(v.data.vaults||[]); setRows(d.data.closings||[]);} useEffect(()=>{load()},[]);
 async function getPreview(){ if(!form.vaultId) return setMsg({error:'Choose a vault first.'}); try{const p=await api.get(`/daily-closing/preview?date=${form.closingDate}&vaultId=${form.vaultId}`); setPreview(p.data.preview); setForm({...form,countedClosing:p.data.preview.expectedClosing}); setMsg({});}catch(err){setMsg({error:err.response?.data?.message||'Preview failed.'})}}
 async function submit(e){e.preventDefault(); try{await api.post('/daily-closing',form); setMsg({success:'Daily closing saved.'}); setPreview(null); await load();}catch(err){setMsg({error:err.response?.data?.message||'Could not save daily closing.'})}}
 return <><PageHeader title="Daily Closing" subtitle="Close the day by vault with income, expenses, exchange movement and difference."/><Alert {...msg}/>
 <section className="panel"><h2>Close Day</h2><form className="form-grid" onSubmit={submit}><label>Date<input type="date" value={form.closingDate} onChange={e=>setForm({...form,closingDate:e.target.value})}/></label><label>Vault<select value={form.vaultId} onChange={e=>setForm({...form,vaultId:e.target.value})}><option value="">Choose vault</option>{vaults.map(v=><option key={v.id} value={v.id}>{v.name} - {v.currency_code} - {Number(v.balance).toFixed(2)}</option>)}</select></label><label>Counted Closing<input type="number" step="0.01" value={form.countedClosing} onChange={e=>setForm({...form,countedClosing:e.target.value})}/></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions"><button type="button" className="secondary" onClick={getPreview}>Preview</button><button>Save Closing</button></div></form></section>
 {preview&&<section className="stats-grid"><div className="stat-card"><span>Opening</span><strong>{Number(preview.openingBalance).toFixed(2)}</strong><small>{preview.vault.currency_code}</small></div><div className="stat-card"><span>Income</span><strong>{Number(preview.totalIncome).toFixed(2)}</strong></div><div className="stat-card"><span>Expenses</span><strong>{Number(preview.totalExpenses).toFixed(2)}</strong></div><div className="stat-card"><span>Exchange In / Out</span><strong>{Number(preview.totalExchangeIn).toFixed(2)} / {Number(preview.totalExchangeOut).toFixed(2)}</strong></div><div className="stat-card"><span>Exchange Profit</span><strong>{Number(preview.exchangeProfit).toFixed(2)}</strong></div><div className="stat-card"><span>Expected Closing</span><strong>{Number(preview.expectedClosing).toFixed(2)}</strong></div></section>}
 <section className="panel"><h2>Closing History</h2><div className="table-wrap"><table><thead><tr><th>No</th><th>Date</th><th>Vault</th><th>Opening</th><th>Income</th><th>Expense</th><th>Expected</th><th>Counted</th><th>Diff</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.closing_no}</td><td>{String(r.closing_date).slice(0,10)}</td><td>{r.vault_name}</td><td>{Number(r.opening_balance).toFixed(2)}</td><td>{Number(r.total_income).toFixed(2)}</td><td>{Number(r.total_expenses).toFixed(2)}</td><td>{Number(r.expected_closing).toFixed(2)}</td><td>{Number(r.counted_closing).toFixed(2)}</td><td>{Number(r.difference).toFixed(2)}</td><td>{r.status}</td></tr>)}</tbody></table></div></section></>;
}
