import { useEffect, useState } from 'react';
import api from '../services/api';
import PageHeader from '../components/PageHeader';
import Alert from '../components/Alert';
export default function OpeningBalance(){
 const [people,setPeople]=useState([]),[vaults,setVaults]=useState([]),[rows,setRows]=useState([]),[msg,setMsg]=useState({});
 const [form,setForm]=useState({balanceType:'CUSTOMER',personId:'',vaultId:'',amount:'',currencyCode:'USD',notes:''});
 async function load(){const [p,v,o]=await Promise.all([api.get('/people'),api.get('/vaults'),api.get('/opening-balances')]); setPeople(p.data.people||[]); setVaults(v.data.vaults||[]); setRows(o.data.openingBalances||[]);} useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault(); try{await api.post('/opening-balances',{...form, personId:form.personId||null, vaultId:form.vaultId||null}); setMsg({success:'Opening balance saved and posted to journal.'}); setForm({...form,amount:'',notes:''}); await load();}catch(err){setMsg({error:err.response?.data?.message||'Could not save opening balance.'})}}
 return <><PageHeader title="Opening Balance" subtitle="Enter starting balances for customers, suppliers, vault, cash and bank"/><Alert {...msg}/><section className="panel"><h2>Add Opening Balance</h2><form className="form-grid" onSubmit={submit}><label>Type<select value={form.balanceType} onChange={e=>setForm({...form,balanceType:e.target.value})}><option>CUSTOMER</option><option>SUPPLIER</option><option>VAULT</option><option>CASH</option><option>BANK</option></select></label><label>Currency<input value={form.currencyCode} onChange={e=>setForm({...form,currencyCode:e.target.value})}/></label><label>Customer/Supplier<select value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}><option value="">None</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} - {p.person_type}</option>)}</select></label><label>Vault/Cash/Bank<select value={form.vaultId} onChange={e=>setForm({...form,vaultId:e.target.value})}><option value="">None</option>{vaults.map(v=><option key={v.id} value={v.id}>{v.name} - {v.currency_code}</option>)}</select></label><label>Amount<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions"><button>Save Opening Balance</button></div></form></section><section className="panel"><h2>Opening Balances</h2><div className="table-wrap"><table><thead><tr><th>No</th><th>Date</th><th>Type</th><th>Person</th><th>Vault</th><th>Amount</th><th>Currency</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.balance_no}</td><td>{String(r.balance_date).slice(0,10)}</td><td>{r.balance_type}</td><td>{r.person_name||'-'}</td><td>{r.vault_name||'-'}</td><td>{Number(r.amount).toFixed(2)}</td><td>{r.currency_code}</td></tr>)}</tbody></table></div></section></>
}
