import { useEffect, useState } from 'react';
import api from '../services/api';
import PageHeader from '../components/PageHeader';
import Alert from '../components/Alert';

export default function Reconciliation(){
 const [rows,setRows]=useState([]),[people,setPeople]=useState([]),[vaults,setVaults]=useState([]),[summary,setSummary]=useState([]),[msg,setMsg]=useState({});
 const [form,setForm]=useState({reconciliationType:'VAULT',personId:'',vaultId:'',countedBalance:'',notes:''});
 async function load(){const [r,p,v,s]=await Promise.all([api.get('/reconciliation'),api.get('/people'),api.get('/vaults'),api.get('/reconciliation/summary')]); setRows(r.data.reconciliations||[]); setPeople(p.data.people||[]); setVaults(v.data.vaults||[]); setSummary(s.data.summary||[]);} 
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault(); try{await api.post('/reconciliation',{...form,personId:form.personId||null,vaultId:form.vaultId||null}); setMsg({success:'Reconciliation saved and posted to journal.'}); setForm({...form,countedBalance:'',notes:''}); await load();}catch(err){setMsg({error:err.response?.data?.message||'Could not save reconciliation.'})}}
 return <><PageHeader title="Reconciliation" subtitle="Compare system balance with counted cash, vault, bank, customer or supplier balance."/><Alert {...msg}/>
 <section className="stats-grid">{summary.map((s,i)=><div className="stat-card" key={i}><span>{s.reconciliation_type} {s.currency_code}</span><strong>{Number(s.total_difference).toFixed(2)}</strong><small>{s.count} records difference total</small></div>)}</section>
 <section className="panel"><h2>New Reconciliation</h2><form className="form-grid" onSubmit={submit}><label>Type<select value={form.reconciliationType} onChange={e=>setForm({...form,reconciliationType:e.target.value})}><option>VAULT</option><option>CASH</option><option>BANK</option><option>CUSTOMER</option><option>SUPPLIER</option></select></label><label>Customer/Supplier<select value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}><option value="">None</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} - {p.person_type}</option>)}</select></label><label>Vault/Cash/Bank<select value={form.vaultId} onChange={e=>setForm({...form,vaultId:e.target.value})}><option value="">None</option>{vaults.map(v=><option key={v.id} value={v.id}>{v.name} - {v.currency_code} - {Number(v.balance).toFixed(2)}</option>)}</select></label><label>Counted Balance<input type="number" step="0.01" value={form.countedBalance} onChange={e=>setForm({...form,countedBalance:e.target.value})}/></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions"><button>Save Reconciliation</button></div></form></section>
 <section className="panel"><h2>Reconciliation History</h2><div className="table-wrap"><table><thead><tr><th>No</th><th>Date</th><th>Type</th><th>Person</th><th>Vault</th><th>System</th><th>Counted</th><th>Diff</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.reconciliation_no}</td><td>{String(r.reconciliation_date).slice(0,10)}</td><td>{r.reconciliation_type}</td><td>{r.person_name||'-'}</td><td>{r.vault_name||'-'}</td><td>{Number(r.system_balance).toFixed(2)} {r.currency_code}</td><td>{Number(r.counted_balance).toFixed(2)}</td><td>{Number(r.difference).toFixed(2)}</td><td>{r.status}</td></tr>)}</tbody></table></div></section></>;
}
